services:
  postgres:
    build:
      context: .  # Use the current directory where the Dockerfile is located
      dockerfile: Dockerfile
    container_name: postgres_db  # Optional: specify a custom container name
    ports:
      - "5432:3306"  # Map host port 8080 to container port 8080 (if needed)
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    tty: true  # Keep the container running with an interactive shell
    env_file: 
        .env
