services:

  db:
    image: postgres
    restart: always
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./entrypoint.sh:/usr/bin/entrypoint.sh
    user: postgres
    entrypoint: ["/usr/bin/entrypoint.sh"]
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DB_TABLE_NAME: ${DB_TABLE_NAME}
    stop_grace_period: 30s

  evm:
    build: .
    restart: always
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - ./config.toml:/config.toml
